# Generated by Django 4.1.2 on 2022-10-21 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компании')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), size=1000)),
                ('start_date', models.DateTimeField(verbose_name='Начало обзвона')),
                ('end_date', models.DateTimeField(verbose_name='Окончание обзвона')),
                ('status', models.CharField(choices=[('new', 'новая'), ('on moderation', 'на модерации'), ('running', 'запущена'), ('stoped', 'остановлена'), ('complete', 'завершена')], default='new', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
