# Generated by Django 4.1.2 on 2022-10-21 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=1000),
        ),
    ]
