# Generated by Django 4.1.2 on 2022-10-22 07:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_company_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), size=10000),
        ),
    ]
